
SKYPOND_INC = ../include

all:
	gcc main.cpp -I$(SKYPOND_INC) -I/usr/local/include -I/usr/local/include/SDL2 -I-L/usr/local/lib \
	-I$(HOME)/SDL/SDL2_ttf-2.22.0/_install/include \
	-L$(HOME)/SDL/SDL2_ttf-2.22.0/_install/lib -lSDL2 -lSDL2_ttf -lSDL2_image -o main

