# files of SKYPOND
SKYPOND_SRC = $(SKYPOND_HOME)/src
SKYPOND_SRCS := $(shell find $(SKYPOND_SRC) -name "*.cpp")
SKYPOND_INC = $(SKYPOND_HOME)/include
SKYPOND_USR_INC = $(SKYPOND_HOME)/usr/include
INC_PATH += $(SKYPOND_USR_INC)

SKYPOND_BUILD_DIR = $(SKYPOND_HOME)/build
SKYPOND_OBJS := $(addprefix $(SKYPOND_BUILD_DIR)/, $(addsuffix .o, $(basename $(notdir $(SKYPOND_SRCS)))))

# The archive of SKYPOND
SKYPOND_ARCHIVE = $(SKYPOND_BUILD_DIR)/SKYPOND.a
CXXFLAGS += -MMD -O3 $(shell sdl2-config --cflags)

$(SKYPOND_BUILD_DIR)/%.o: $(SKYPOND_SRC)/%.cpp
	@echo + CXX "->" SKYPOND_HOME/$(shell realpath $< --relative-to $(SKYPOND_HOME))
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXF-i$()LAGS) -I$(SKYPOND_INC)   -c -o $@ $< -L$(HOME)/SDL/SDL2_ttf-2.22.0/_install/lib -lSDL2_ttf

# Build the archive of SKYPOND
$(SKYPOND_ARCHIVE): $(SKYPOND_OBJS)
	@echo + AR "->" $(shell realpath $@ --relative-to $(SKYPOND_HOME))
	@ar rcs $(SKYPOND_ARCHIVE) $(SKYPOND_OBJS)

# Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(SKYPOND_OBJS:.o=.d)

# Link flags for examples
LDFLAGS += $(shell sdl2-config --libs) -lSDL2_image -L$(HOME)/SDL/SDL2_ttf-2.22.0/_install/lib -lSDL2_ttf

.PHONY: SKYPOND-archive SKYPOND-clean

skypond-archive: $(SKYPOND_ARCHIVE)

skypond-clean:
	rm -rf $(SKYPOND_BUILD_DIR)
